/* GENERATED FILE — hand-seeded placeholder, will be regenerated by
 * `cargo build` (see core/build.rs, which runs cbindgen against
 * core/src/lib.rs) the first time this crate builds on a machine with the
 * Rust toolchain installed. Do not hand-edit once that has happened —
 * this file exists only so iOS/Swift scaffolding has something to
 * `#import` before that first real build. See ADR 0002 §9.
 */

#ifndef VNADDR_H
#define VNADDR_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum VnaddrStatus {
  VnaddrStatus_Ok = 0,
  VnaddrStatus_NotOpen = 1,
  VnaddrStatus_InvalidArgument = 2,
  VnaddrStatus_Panicked = 3,
  VnaddrStatus_IoError = 4,
} VnaddrStatus;

uint32_t vnaddr_abi_version(void);

int32_t vnaddr_ping(void);

enum VnaddrStatus vnaddr_open(const char *dir);

bool vnaddr_is_open(void);

char *vnaddr_active_dataset_dir(void);

void vnaddr_free_string(char *s);

#ifdef __cplusplus
}
#endif

#endif /* VNADDR_H */
